title: My awesome title
author: Mar
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Github practice
theme: minima
# social links
twitter_username: x # DO NOT include the @ character, or else the build will fail!
github_username:  x # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
